name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10'
          registry-url: 'https://registry.npmjs.org'
      - name: yarn install
        run: yarn install
      - name: Install peer dependencies
        run: |
          chmod +x ./tests/prepare-dev.sh
          ./tests/prepare-dev.sh
      - name: Rebuilding firebase
        run: npm rebuild && npm run prepare --if-present
      - name: yarn build
        run: yarn build
      - name: yarn test
        run: yarn test
      - name: Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml
          fail_ci_if_error: false
