name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10'
          registry-url: 'https://registry.npmjs.org'
      - name: yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - name: Install peer dependencies
        run: |
          chmod +x ./tests/prepare-dev.sh
          ./tests/prepare-dev.sh
      - name: Rebuilding firebase
        run: npm rebuild && npm run prepare --if-present
      - name: yarn build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command
      - name: yarn test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test # will run `yarn test` command
      - name: Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          file: ./coverage/clover.xml #optional
          fail_ci_if_error: false
